Feature/cosmosdb crud
KTC-Security-Circle/SC-system-ai pull request #146
Opened 2024-12-20 15:26 UTC by haruki26

## 概要

CosmosDBManagerにCRUDを実装する

## 変更点

このセクションでは、具体的な変更点や修正箇所を箇条書きでリストアップしてください。

- ドキュメントをフォーマットする関数を作成
- similarity_search_with_scoreで返却値のmetadataにidを付与する処理を追加
- get_source_by_idでクエリを使用する形に変更
- ベクターストアにドキュメントを追加するメソッドを作成
- ベクターストアのドキュメントを更新するメソッドを作成

ドキュメントの削除は継承元のdelete_document_by_idで行えることを確認しました。

## 関連Issue

このセクションでは、このPRが関連するIssueをリンクしてください。以下のように記述します。

- 関連Issue: #109

2024-12-20 16:02 UTC, haruki26 commented
とりあえずですが作成しました。イメージと違うとこあったら教えてください。

2024-12-23 14:10 UTC, snow7y requested changes
以前の自分のコードの部分かもですが、気になった部分をレビューしました
あとazure.coreのloggerがうるさかったのでワーニング以上のlogしか出力されないように変更するコードを別途プッシュするのでプルお願いします

2024-12-23 14:10 UTC, snow7y commented on src/sc_system_ai/template/azure_cosmos.py
> +        query = "SELECT c.metadata FROM c WHERE c.id = " + f"'{id}'"
ここでf-stringで埋め込んでいるが、_similarity_search_with_scoreメソッドのようにparametersを使用して埋め込んであげたほうがよさそう

```
query = "SELECT c.metadata FROM c WHERE c.id = @id"
parameters = [{"name": "@id", "value": id}]
item = self._container.query_items(
query=query, parameters=parameters, enable_cross_partition_query=True
).next()
```

2024-12-23 14:10 UTC, snow7y commented on src/sc_system_ai/template/document_formatter.py
> +    level = 0
re module使ったらもう少し簡単に書ける

```
headers = re.findall(r"^#+", text, re.MULTILINE)
return max([len(h) for h in headers]) if headers else 0
```

2024-12-24 06:29 UTC, haruki26 commented on src/sc_system_ai/template/azure_cosmos.py
> +        query = "SELECT c.metadata FROM c WHERE c.id = " + f"'{id}'"
query_itemメソッドが`parameters`に`list[dict[str, object]]`をふっているせいかmypyエラー出ます。
cast関数で`list[dict[str, Any]]`にしています。

2024-12-25 10:50 UTC, snow7y commented on src/sc_system_ai/template/azure_cosmos.py
> +        query = "SELECT c.metadata FROM c WHERE c.id = " + f"'{id}'"
> query_itemメソッドが`parameters`に`list[dict[str, object]]`をふっているせいかmypyエラー出ます。 cast関数で`list[dict[str, Any]]`にするとエラー吐かないのでキャストしてます。

良いと思います

2024-12-25 10:51 UTC, snow7y approved these changes

2024-12-28 08:24 UTC, haruki26 commented
ツールの動作確認しました。現在、ベクターサーチの結果からidを取得してidでもう一度クエリした結果を返すようになっているのですが、ベクターサーチの結果をそのまま返すようにしても問題無いでしょうか？

2025-01-06 01:00 UTC, haruki26 commented
langchain側でデフォルトでidを取得するようになっていたのでオーバーライドを削除しました。

2025-01-06 14:21 UTC, merged