Feature/streaming response
KTC-Security-Circle/SC-system-ai pull request #63
Opened 2024-10-16 15:32 UTC by haruki26

## 概要

ストリーミング機能を持ったエージェントの作成

## 変更点
- 変更点1: AgentとTool用のHandlerを作成
- 変更点2: Streaming機能を持ったAgentを作成
- 変更点3: Agent基底クラスにStreaming機能を追加

## 関連Issue
- 関連Issue: #40

2024-10-17 14:36 UTC, snow7y requested changes
コードは動くのを確認できましたし、コードもよさそうです。
現在MainAgentを基底クラスとして継承してますが、template/agent.pyのAgentクラスにこのコードを導入すればほかの他のagents/のクラスで使用できるようになるかなと思います。
この変更を検討してみてください

2024-10-17 14:36 UTC, snow7y commented on src/sc_system_ai/agents/streaming_agent.py
> +        self,
できれば型指定もやってあげたほうがいいかも？

2024-10-18 15:39 UTC, haruki26 commented on src/sc_system_ai/agents/streaming_agent.py
> +        self,
ほぼ勉強ファイル的な立ち位置になってしまったのでstudiesに移動しようかなと思っています

2024-10-19 15:00 UTC, snow7y requested changes
このコードを動かしたところ、
`AttributeError: 'Agent' object has no attribute 'queue'`
が発生してエラーになります。
私の環境だけなのか確認お願いします。

2024-10-19 15:27 UTC, haruki26 commented on src/sc_system_ai/template/agent.py
>      def invoke(self, message: str):
最初その形で作ったんですがyield置くとジェネレータとしてみなされるようで、実行すらされなかったんですよね。
[無理矢理やる方法](https://qiita.com/Daizoo/items/370901ae28c1f586b093)もあるにはあるんですがよろしくはないようなのでやめときました。
実行時のis_streamingの変更についてですが、セッターみたいなの用意してその中で再度create_invoke実行みたいな形はどうでしょうか？
それかもうinvokeわけちゃった方が早いかと

2024-10-19 15:38 UTC, snow7y commented on src/sc_system_ai/template/agent.py
>      def invoke(self, message: str):
AIに書かせたこのコードやったらうまくいってそう
おそらくfromを付けてるかどうかかな？

その辺の違いも見つつ、一度試してみて
この部分だけreturnをyieldぽく返す形にして両方yieldで動く形にするのもありかも

2024-10-24 15:21 UTC, snow7y approved these changes
問題ないです！

2024-10-24 23:23 UTC, merged